### ISSUE TITLE
NullPointerException in SkuDetailsWrapper

### ISSUE THREAD

**Issue by tlozovyi** [apphud/ApphudSDK-Android#51] opened 2022-07-06 10:11 UTC
Hi,

I'm receiving crash in Crashlytics for reasonable amount of users:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.android.billingclient.api.PurchaseHistoryRecord.e()' on a null object reference
       at com.apphud.sdk.internal.SkuDetailsWrapper.restoreAsync(SkuDetailsWrapper.kt:26)
       at com.apphud.sdk.internal.BillingWrapper$restore$1.invokeSuspend(BillingWrapper.kt:137)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by DimaDDM** [comment] 2022-11-26 09:24
Still not fixed!

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.android.billingclient.api.PurchaseHistoryRecord.c()' on a null object reference
       at com.apphud.sdk.internal.SkuDetailsWrapper.restoreAsync(SkuDetailsWrapper.kt:26)
       at com.apphud.sdk.internal.BillingWrapper$restore$1.invokeSuspend(BillingWrapper.kt:137)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

**Comment by vladimir-slatvinskiy** [comment] 2022-11-27 07:50
hi guys, what version of sdk are you using?

**Comment by DimaDDM** [comment] 2022-11-27 10:36
> hi guys, what version of sdk are you using?

1.65 now and in early versions this case repeating too. I send report few month ago to support but no luck. It's crashing apps on first start usually. CRITICAL bug :(

**Comment by vladimir-slatvinskiy** [comment] 2022-12-08 09:19
Hmm, need additional info from you. Are you able to reproduce issue on you own test device? I can't reproduce the problem on my.

**Comment by DimaDDM** [comment] 2022-12-23 15:44
> Hmm, need additional info from you. Are you able to reproduce issue on you own test device? I can't reproduce the problem on my.

Looks like problem gone on 1.6.8. 1.7.0 didn't test. Scary

**Comment by ren6** [comment] 2022-12-26 03:59
Hello! We couldn't reproduce this bug as none of our other clients. I assume your issue has been fixed. Closing for now.

**Closed by ren6** 2022-12-26 03:59 UTC
